package com.tan.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class Product {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tj_product.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tj_product.category_id
     *
     * @mbggenerated
     */
    private Integer categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tj_product.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tj_product.subtitle
     *
     * @mbggenerated
     */
    private String subtitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tj_product.main_image
     *
     * @mbggenerated
     */
    private String mainImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tj_product.price
     *
     * @mbggenerated
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tj_product.stock
     *
     * @mbggenerated
     */
    private Integer stock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tj_product.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tj_product.is_new
     *
     * @mbggenerated
     */
    private Boolean isNew;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tj_product.is_hot
     *
     * @mbggenerated
     */
    private Boolean isHot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tj_product.is_banner
     *
     * @mbggenerated
     */
    private Boolean isBanner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tj_product.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tj_product.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tj_product.sub_image
     *
     * @mbggenerated
     */
    private String subImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tj_product.detail
     *
     * @mbggenerated
     */
    private String detail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tj_product.id
     *
     * @return the value of tj_product.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tj_product.id
     *
     * @param id the value for tj_product.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tj_product.category_id
     *
     * @return the value of tj_product.category_id
     *
     * @mbggenerated
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tj_product.category_id
     *
     * @param categoryId the value for tj_product.category_id
     *
     * @mbggenerated
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tj_product.name
     *
     * @return the value of tj_product.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tj_product.name
     *
     * @param name the value for tj_product.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tj_product.subtitle
     *
     * @return the value of tj_product.subtitle
     *
     * @mbggenerated
     */
    public String getSubtitle() {
        return subtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tj_product.subtitle
     *
     * @param subtitle the value for tj_product.subtitle
     *
     * @mbggenerated
     */
    public void setSubtitle(String subtitle) {
        this.subtitle = subtitle == null ? null : subtitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tj_product.main_image
     *
     * @return the value of tj_product.main_image
     *
     * @mbggenerated
     */
    public String getMainImage() {
        return mainImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tj_product.main_image
     *
     * @param mainImage the value for tj_product.main_image
     *
     * @mbggenerated
     */
    public void setMainImage(String mainImage) {
        this.mainImage = mainImage == null ? null : mainImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tj_product.price
     *
     * @return the value of tj_product.price
     *
     * @mbggenerated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tj_product.price
     *
     * @param price the value for tj_product.price
     *
     * @mbggenerated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tj_product.stock
     *
     * @return the value of tj_product.stock
     *
     * @mbggenerated
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tj_product.stock
     *
     * @param stock the value for tj_product.stock
     *
     * @mbggenerated
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tj_product.status
     *
     * @return the value of tj_product.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tj_product.status
     *
     * @param status the value for tj_product.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tj_product.is_new
     *
     * @return the value of tj_product.is_new
     *
     * @mbggenerated
     */
    public Boolean getIsNew() {
        return isNew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tj_product.is_new
     *
     * @param isNew the value for tj_product.is_new
     *
     * @mbggenerated
     */
    public void setIsNew(Boolean isNew) {
        this.isNew = isNew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tj_product.is_hot
     *
     * @return the value of tj_product.is_hot
     *
     * @mbggenerated
     */
    public Boolean getIsHot() {
        return isHot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tj_product.is_hot
     *
     * @param isHot the value for tj_product.is_hot
     *
     * @mbggenerated
     */
    public void setIsHot(Boolean isHot) {
        this.isHot = isHot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tj_product.is_banner
     *
     * @return the value of tj_product.is_banner
     *
     * @mbggenerated
     */
    public Boolean getIsBanner() {
        return isBanner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tj_product.is_banner
     *
     * @param isBanner the value for tj_product.is_banner
     *
     * @mbggenerated
     */
    public void setIsBanner(Boolean isBanner) {
        this.isBanner = isBanner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tj_product.create_time
     *
     * @return the value of tj_product.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tj_product.create_time
     *
     * @param createTime the value for tj_product.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tj_product.update_time
     *
     * @return the value of tj_product.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tj_product.update_time
     *
     * @param updateTime the value for tj_product.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tj_product.sub_image
     *
     * @return the value of tj_product.sub_image
     *
     * @mbggenerated
     */
    public String getSubImage() {
        return subImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tj_product.sub_image
     *
     * @param subImage the value for tj_product.sub_image
     *
     * @mbggenerated
     */
    public void setSubImage(String subImage) {
        this.subImage = subImage == null ? null : subImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tj_product.detail
     *
     * @return the value of tj_product.detail
     *
     * @mbggenerated
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tj_product.detail
     *
     * @param detail the value for tj_product.detail
     *
     * @mbggenerated
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }
}